import "./globals.css";
import type { Metadata } from "next";
import { BrFirma } from "@/font";
import Sidebar from "@/components/features/sidebar";
import MainHeader from "@/components/header/mainHeader";
import { cn } from "@/lib/utils";
import Providers from "@/lib/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(BrFirma.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}

// import "./globals.css";
// import type { Metadata } from "next";
// import { BrFirma } from "@/font";
// import Sidebar from "@/components/features/sidebar";
// import MainHeader from "@/components/header/mainHeader";
// import { cn } from "@/lib/utils";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body className={cn(BrFirma.className)}>
//         <div className="flex flex-col h-screen ">
//           <MainHeader />
//           <div className="flex flex-1 ">
//             <div>
//               <Sidebar />
//             </div>
//             <div className="w-full">{children}</div>
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }
