import "./globals.css";
import type { Metadata } from "next";
import { BrFirma } from "@/font";
import Sidebar from "@/components/features/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={BrFirma.className}>
        <div className="flex">
          <div>
            <Sidebar />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
